# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be8b433915b9fe85542565d9dc5191225aadf2ab8498461e9e6e02174f0ed638669185afba901fc14c9a6409d2cfb34befa6c2350465d078b04aa43536f6e0af

test:
  secret_key_base: df77fb60524decad05068bb7892b91ec9fc8be25962abf925031bc85825aeb2c2e216e26325ae440b5972fe79f0386df9b58898473d4ec482bac651e094deba2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
